# Generated by Django 3.1.1 on 2020-09-30 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Кличка')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='Вес')),
                ('number', models.ImageField(max_length=30, upload_to='', verbose_name='Номер')),
                ('age', models.PositiveBigIntegerField(default=0, verbose_name='Возраст')),
                ('image', models.ImageField(upload_to='animal/', verbose_name='Изображение')),
                ('extra_photo', models.ImageField(upload_to='animal/', verbose_name='Дополнительное фото')),
                ('size', models.CharField(max_length=60, verbose_name='Размер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('go_to_shelter', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Дата поступления в приют')),
                ('temperament', models.CharField(max_length=60, verbose_name='Темперамент')),
                ('character', models.TextField(verbose_name='Характер')),
                ('health', models.CharField(max_length=100, verbose_name='Здоровье')),
                ('vaccination', models.TextField(verbose_name='Прививки')),
                ('sterilize', models.BooleanField(verbose_name='Стерилизация')),
                ('video', models.FilePathField(verbose_name='Видео')),
                ('needs', models.CharField(max_length=100, verbose_name='Нужды')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Порода животного')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Вид',
            },
        ),
        migrations.CreateModel(
            name='Rewies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appShelter.animal', verbose_name='Животное')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appShelter.rewies', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ManyToManyField(to='appShelter.Breed', verbose_name='порода'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sort',
            field=models.ManyToManyField(related_name='animal_gender', to='appShelter.Gender', verbose_name='пол'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.ManyToManyField(to='appShelter.Type', verbose_name='вид'),
        ),
    ]
