# Generated by Django 3.1.1 on 2020-09-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Вид', 'verbose_name_plural': 'Виды'},
        ),
    ]
