# Generated by Django 3.1.1 on 2020-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Вид', 'verbose_name_plural': 'Виды'},
        ),
        migrations.AddField(
            model_name='animal',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='character',
            field=models.TextField(default='', verbose_name='Характер'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='extra_photo',
            field=models.ImageField(default='default.jpg', upload_to='animal/', verbose_name='Дополнительное фото'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health',
            field=models.CharField(default='', max_length=100, verbose_name='Здоровье'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='animal/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='needs',
            field=models.CharField(default='', max_length=100, verbose_name='Нужды'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='number',
            field=models.IntegerField(default='', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(default='', max_length=60, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sterilize',
            field=models.BooleanField(default='', verbose_name='Стерилизация'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='temperament',
            field=models.CharField(default='', max_length=60, verbose_name='Темперамент'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccination',
            field=models.TextField(default='', verbose_name='Прививки'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='upload_location', verbose_name='Видео'),
        ),
    ]
