# Generated by Django 3.1.1 on 2020-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShelter', '0002_auto_20201001_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Прививки')),
            ],
            options={
                'verbose_name': 'Прививка',
                'verbose_name_plural': 'Прививки',
            },
        ),
        migrations.RemoveField(
            model_name='animal',
            name='size',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='vaccination',
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.ManyToManyField(to='appShelter.Size', verbose_name='размер'),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccination',
            field=models.ManyToManyField(to='appShelter.Vaccination', verbose_name='прививки'),
        ),
    ]
