# Generated by Django 3.1.1 on 2020-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShelter', '0003_auto_20201001_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Возраст',
                'verbose_name_plural': 'Возраста',
            },
        ),
        migrations.CreateModel(
            name='Temperament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Темперамент')),
            ],
            options={
                'verbose_name': 'Темперамент',
                'verbose_name_plural': 'Темпераменты',
            },
        ),
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='temperament',
        ),
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.ManyToManyField(to='appShelter.Age', verbose_name='возраст'),
        ),
        migrations.AddField(
            model_name='animal',
            name='temperament',
            field=models.ManyToManyField(to='appShelter.Temperament', verbose_name='темперамент'),
        ),
    ]
