# Generated by Django 3.1.2 on 2020-10-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShelter', '0004_auto_20201001_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='sort',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='vaccination',
        ),
        migrations.AlterField(
            model_name='temperament',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Темперамент'),
        ),
    ]
