# Generated by Django 3.1.2 on 2020-10-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShelter', '0006_auto_20201029_1503'),
        ('appShelter', '0006_auto_20201029_1825'),
    ]

    operations = [
    ]
